### PR TITLE
Firestore rules and tests

### PR DESCRIPTION
**Pull request by magicalbeacon**
This PR aims to add rules and validation to the `hawkers` table, will need structure for the other tables for me to be able to add more rules for it, for now, I've added the `deliveries` and `cuisines` table with some default rules, and more granularity for `hawkers` table. Please let me know if any of the table names are wrong. I've also added a `test.js` file with `mocha` for Firestore rules unit tests.

### CODE REVIEW

**Comment by magicalbeacon** [comment]
Weird, checks are failing now :/

**Comment by limyifan1** [comment]
Sorry about that, I believe it might be because of certain PRs and commits we made. Couldn't quite isolate why the tests are failing...

**Comment by magicalbeacon** [comment]
> 
> 
> Sorry about that, I believe it might be because of certain PRs and commits we made. Couldn't quite isolate why the tests are failing...

It seems like an unresolved merge conflict from what I see.

**Comment by magicalbeacon** [comment]
Here's a file that I spotted in your commit that has an unresolved merge conflict:
https://github.com/limyifan1/hawkercentral/blob/8ef1517fc250a97f091c461b1e0834bcdf23fb0c/src/Components/ListForm.js

**Comment by limyifan1** [comment]
Fixing in progress!

**Comment by joycesin** [comment]
done! there shouldn't be any more merge conflicts on master now

**Comment by magicalbeacon** [comment]
I've updated the rules, tests and some documentation on how to test them to the latest structure of database, I'm following the structure in `ListForm.js` since it's a chore for you to continuously update the README.

**Comment by achrinza** [comment]
It's recommended to not merge master into the feature branch. Instead the following should be done:

1.  Rebase fork master against upstream master
```sh
git pull rebase --upstream master
```

2.  Rebase fork feature branch again fork master
```
git rebase master
```

This will help keep the git commit log clean and prevent commit linting issues.

**Comment by limyifan1** [comment]
Just tried the unit tests for the new rules, amazing work :) will do some more checks then merge it

**Comment by limyifan1** [comment]
This works really well. Thanks so much :) would never have been able to figure out all these rules an tests...

**Comment by magicalbeacon** [comment]
> 
> 
> This works really well. Thanks so much :) would never have been able to figure out all these rules an tests...

All good! Although they are simple for now, it creates a bottom line for security rules, as your tables become more finalised, we can add more stringent rules for them, I'll continue to work on them when I'm free :)

As always, feel free to let me know if you need help with anything pertaining to Firebase!

**Pull request merged**
